name: sentiment_analyzer_env
channels:
  - conda-forge
dependencies:
  - python==3.11.0
  - numpy==1.23.5
  - pandas==2.2.2
  - scikit-learn==1.5.1
  - seaborn==0.13.2
  - matplotlib==3.9.2
  - transformers==4.46.3
  - nltk==3.9.1
  - spacy==3.7.5
  - wordcloud==1.9.4
